Importing the required libraries

In [1]:
import pandas as pd

import numpy as np

import random

load and read dataset

Dataset : https://www.kaggle.com/sootersaalu/amazon-top-50-bestselling-books-2009-2019

In [2]:
bestsellers_data = pd.read_csv('datasets/BestsellersWithCategories.csv')

bestsellers_data.head(10)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
5,A Dance with Dragons (A Song of Ice and Fire),George R. R. Martin,4.4,12643,11,2011,Fiction
6,A Game of Thrones / A Clash of Kings / A Storm...,George R. R. Martin,4.7,19735,30,2014,Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
8,"A Higher Loyalty: Truth, Lies, and Leadership",James Comey,4.7,5983,3,2018,Non Fiction
9,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2016,Fiction

In [3]:
bestsellers_data.columns = [column.replace(' ', '_') for column in bestsellers_data.columns]

In [4]:
bestsellers_data.tail()

,Name,Author,User_Rating,Reviews,Price,Year,Genre
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413,8,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2018,Non Fiction
549,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2019,Non Fiction

In [5]:
bestsellers_data.shape

(550, 7)

In [6]:
bestsellers_data.isnull().sum()

Name           0
Author         0
User_Rating    0
Reviews        0
Price          0
Year           0
Genre          0
dtype: int64

Simple random sampling: 
 - A simple random sample is a randomly selected subset of a population. In this sampling method, each member of the population has an exactly equal chance of being selected.

In [7]:
samp_sr1 = bestsellers_data.sample(n=10)

In [8]:
samp_sr1

,Name,Author,User_Rating,Reviews,Price,Year,Genre
508,To Kill a Mockingbird,Harper Lee,4.8,26234,0,2016,Fiction
168,How to Win Friends & Influence People,Dale Carnegie,4.7,25001,11,2016,Non Fiction
414,The Immortal Life of Henrietta Lacks,Rebecca Skloot,4.7,9289,9,2012,Non Fiction
279,Publication Manual of the American Psychologic...,American Psychological Association,4.5,8580,46,2017,Non Fiction
509,To Kill a Mockingbird,Harper Lee,4.8,26234,7,2019,Fiction
524,Watchmen,Alan Moore,4.8,3829,42,2009,Fiction
118,Game of Thrones Boxed Set: A Game of Thrones/A...,George R.R. Martin,4.6,5594,5,2011,Fiction
82,Dog Man: A Tale of Two Kitties: From the Creat...,Dav Pilkey,4.9,4786,8,2017,Fiction
159,Harry Potter Paperback Box Set (Books 1-7),J. K. Rowling,4.8,13471,52,2016,Fiction
161,Heaven is for Real: A Little Boy's Astounding ...,Todd Burpo,4.7,15779,10,2011,Non Fiction

In [9]:
samp_sr2 = bestsellers_data.sample(n=20)

In [10]:
samp_sr2

,Name,Author,User_Rating,Reviews,Price,Year,Genre
320,The 5 Love Languages: The Secret to Love That ...,Gary Chapman,4.7,3477,28,2010,Non Fiction
433,The Martian,Andy Weir,4.7,39459,9,2015,Fiction
17,Adult Coloring Book: Stress Relieving Patterns,Blue Star Coloring,4.4,2951,6,2015,Non Fiction
378,The Four Agreements: A Practical Guide to Pers...,Don Miguel Ruiz,4.7,23308,6,2017,Non Fiction
93,Eat to Live: The Amazing Nutrient-Rich Program...,Joel Fuhrman MD,4.5,6346,9,2011,Non Fiction
410,The Hunger Games Trilogy Boxed Set (1),Suzanne Collins,4.8,16949,30,2011,Fiction
112,First 100 Words,Roger Priddy,4.7,17323,4,2016,Non Fiction
75,Divergent,Veronica Roth,4.6,27098,15,2013,Fiction
262,P is for Potty! (Sesame Street) (Lift-the-Flap),Naomi Kleinberg,4.7,10820,5,2018,Non Fiction
169,How to Win Friends & Influence People,Dale Carnegie,4.7,25001,11,2017,Non Fiction
142,Good to Great: Why Some Companies Make the Lea...,Jim Collins,4.5,3457,14,2012,Non Fiction
173,Humans of New York,Brandon Stanton,4.8,3490,15,2014,Non Fiction
56,Cutting for Stone,Abraham Verghese,4.6,4866,11,2010,Fiction
487,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842,10,2017,Fiction
319,The 4 Hour Body: An Uncommon Guide to Rapid Fa...,Timothy Ferriss,4.3,4587,21,2011,Non Fiction
469,"The Throne of Fire (The Kane Chronicles, Book 2)",Rick Riordan,4.7,1463,10,2011,Fiction
510,"Tools of Titans: The Tactics, Routines, and Ha...",Timothy Ferriss,4.6,4360,21,2017,Non Fiction
337,The 7 Habits of Highly Effective People: Power...,Stephen R. Covey,4.7,4725,16,2017,Non Fiction
329,The 5 Love Languages: The Secret to Love that ...,Gary Chapman,4.8,25554,8,2019,Non Fiction
327,The 5 Love Languages: The Secret to Love that ...,Gary Chapman,4.8,25554,8,2017,Non Fiction

In [11]:
samp_sr3 = bestsellers_data.sample(n=250, replace='False')

samp_sr3.shape

(250, 7)

In [12]:
bestsellers_data['User_Rating'].sample(n=5, random_state=1)

160    4.8
306    4.0
65     4.8
423    4.5
135    4.0
Name: User_Rating, dtype: float64

In [13]:
bestsellers_data['User_Rating'].sample(n=5, random_state=1)

160    4.8
306    4.0
65     4.8
423    4.5
135    4.0
Name: User_Rating, dtype: float64

In [14]:
bestsellers_data['User_Rating'].sample(n=12, random_state=1)

160    4.8
306    4.0
65     4.8
423    4.5
135    4.0
207    4.9
312    4.0
295    4.7
270    4.3
364    4.0
461    4.6
534    4.8
Name: User_Rating, dtype: float64

In [15]:
bestsellers_data.groupby('Genre')

In [16]:
bestsellers_data.groupby('Genre').mean()

             User_Rating       Reviews      Price         Year
Genre
Fiction         4.648333  15683.791667  10.850000  2013.925000
Non Fiction     4.595161   9065.145161  14.841935  2014.058065

In [17]:
bestsellers_data.groupby('Genre').max()

,Name,Author,User_Rating,Reviews,Price,Year
Genre,,,,,,
Fiction,Wrecking Ball (Diary of a Wimpy Kid Book 14),Wizards RPG Team,4.9,87841,82,2019
Non Fiction,You Are a Badass: How to Stop Doubting Your Gr...,Zhi Gang Sha,4.9,61133,105,2019

Stratified Sampling: 
 - Stratified sampling is a type of sampling method in which the total population is divided into smaller groups or strata to complete the sampling process. The strata is formed based on some common characteristics in the population data.

In [18]:
samp_str1 = bestsellers_data.groupby('Genre')\
                            .apply(lambda x: x.sample(8))

samp_str1

                                                              Name  \
Genre
Fiction     542                                             Wonder
            353                                 The Casual Vacancy
            180                                          If I Stay
            538  Winter of the World: Book Two of the Century T...
            100                                     Fahrenheit 451
            104                                Fifty Shades Darker
            154  Harry Potter and the Cursed Child, Parts 1 & 2...
            46                    Catching Fire (The Hunger Games)
Non Fiction 211                      Laugh-Out-Loud Jokes for Kids
            495                            Thinking, Fast and Slow
            131  Glenn Beck's Common Sense: The Case Against an...
            492                                The Wright Brothers
            526                                      What Happened
            532  Wheat Belly: Lose the Wheat, Lose the Weight, ...
            99   Enchanted Forest: An Inky Quest and Coloring b...
            69   Diagnostic and Statistical Manual of Mental Di...

                                           Author  User_Rating  Reviews  \
Genre
Fiction     542                     R. J. Palacio          4.8    21625
            353                      J.K. Rowling          3.3     9372
            180                      Gayle Forman          4.3     7153
            538                       Ken Follett          4.5    10760
            100                      Ray Bradbury          4.6    10721
            104                         E L James          4.4    23631
            154                      J.K. Rowling          4.0    23973
            46                    Suzanne Collins          4.7    22614
Non Fiction 211                       Rob Elliott          4.6     6990
            495                   Daniel Kahneman          4.6    11034
            131                        Glenn Beck          4.6     1365
            492                  David McCullough          4.7     6169
            526            Hillary Rodham Clinton          4.6     5492
            532                     William Davis          4.4     7497
            99                    Johanna Basford          4.7     5413
            69   American Psychiatric Association          4.5     6679

                 Price  Year        Genre
Genre
Fiction     542      9  2015      Fiction
            353     12  2012      Fiction
            180      9  2014      Fiction
            538     15  2012      Fiction
            100      8  2016      Fiction
            104      7  2012      Fiction
            154     12  2016      Fiction
            46      11  2010      Fiction
Non Fiction 211      4  2016  Non Fiction
            495     19  2012  Non Fiction
            131     11  2009  Non Fiction
            492     16  2015  Non Fiction
            526     18  2017  Non Fiction
            532      6  2013  Non Fiction
            99       9  2015  Non Fiction
            69     105  2013  Non Fiction

In [19]:
samp_str1 = bestsellers_data.groupby('Genre', group_keys=False)\
                            .apply(lambda x: x.sample(8))

samp_str1

,Name,Author,User_Rating,Reviews,Price,Year,Genre
476,The Very Hungry Caterpillar,Eric Carle,4.9,19546,5,2013,Fiction
364,The Elegance of the Hedgehog,Muriel Barbery,4.0,1859,11,2009,Fiction
87,Dog Man: Lord of the Fleas: From the Creator o...,Dav Pilkey,4.9,5470,6,2018,Fiction
156,Harry Potter and the Prisoner of Azkaban: The ...,J.K. Rowling,4.9,3146,30,2017,Fiction
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,14344,5,2017,Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
118,Game of Thrones Boxed Set: A Game of Thrones/A...,George R.R. Martin,4.6,5594,5,2011,Fiction
303,Strange Planet (Strange Planet Series),Nathan W. Pyle,4.9,9382,6,2019,Fiction
295,Secret Garden: An Inky Treasure Hunt and Color...,Johanna Basford,4.7,9366,9,2015,Non Fiction
98,Educated: A Memoir,Tara Westover,4.7,28729,15,2019,Non Fiction
276,Publication Manual of the American Psychologic...,American Psychological Association,4.5,8580,46,2014,Non Fiction
370,The Five Dysfunctions of a Team: A Leadership ...,Patrick Lencioni,4.6,3207,6,2010,Non Fiction
134,Going Rogue: An American Life,Sarah Palin,4.6,1636,6,2009,Non Fiction
464,The Subtle Art of Not Giving a F*ck: A Counter...,Mark Manson,4.6,26490,15,2017,Non Fiction
449,The Plant Paradox Cookbook: 100 Delicious Reci...,Dr. Steven R Gundry MD,4.5,3601,18,2018,Non Fiction
493,"Things That Matter: Three Decades of Passions,...",Charles Krauthammer,4.7,7034,15,2013,Non Fiction

In [20]:
samp_str2 = bestsellers_data.groupby('Genre', group_keys=False)\
                            .apply(lambda x: x.sample(15))

samp_str2

,Name,Author,User_Rating,Reviews,Price,Year,Genre
366,The Fault in Our Stars,John Green,4.7,50482,13,2013,Fiction
395,The Great Gatsby,F. Scott Fitzgerald,4.4,11616,7,2013,Fiction
21,All the Light We Cannot See,Anthony Doerr,4.6,36348,14,2015,Fiction
468,"The Third Wheel (Diary of a Wimpy Kid, Book 7)",Jeff Kinney,4.7,6377,7,2012,Fiction
343,The Blood of Olympus (The Heroes of Olympus (5)),Rick Riordan,4.8,6600,11,2014,Fiction
22,Allegiant,Veronica Roth,3.9,6310,13,2013,Fiction
236,Mockingjay (The Hunger Games),Suzanne Collins,4.5,26741,8,2010,Fiction
135,Gone Girl,Gillian Flynn,4.0,57271,10,2012,Fiction
459,The Shack: Where Tragedy Confronts Eternity,William P. Young,4.6,19720,8,2009,Fiction
259,Orphan Train,Christina Baker Kline,4.6,21930,11,2014,Fiction
456,"The Red Pyramid (The Kane Chronicles, Book 1)",Rick Riordan,4.6,2186,12,2010,Fiction
126,Giraffes Can't Dance,Giles Andreae,4.8,14038,4,2018,Fiction
133,Go the F**k to Sleep,Adam Mansbach,4.8,9568,9,2011,Fiction
398,The Guernsey Literary and Potato Peel Pie Society,Mary Ann Shaffer,4.7,8587,10,2009,Fiction
42,"Cabin Fever (Diary of a Wimpy Kid, Book 6)",Jeff Kinney,4.8,4505,0,2011,Fiction
29,Balance (Angie's Extreme Stress Menders),Angie Grace,4.6,1909,11,2015,Non Fiction
431,The Magnolia Story,Chip Gaines,4.9,7861,5,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2017,Non Fiction
191,Jesus Calling: Enjoying Peace in His Presence ...,Sarah Young,4.9,19576,8,2015,Non Fiction
345,"The Body Keeps the Score: Brain, Mind, and Bod...",Bessel van der Kolk M.D.,4.8,12361,12,2019,Non Fiction
330,The 5000 Year Leap,W. Cleon Skousen,4.8,1680,12,2009,Non Fiction
334,The 7 Habits of Highly Effective People: Power...,Stephen R. Covey,4.6,9325,24,2013,Non Fiction
536,Whose Boat Is This Boat?: Comments That Don't ...,The Staff of The Late Show with,4.6,6669,12,2018,Non Fiction
43,Calm the F*ck Down: An Irreverent Adult Colori...,Sasha O'Hara,4.6,10369,4,2016,Non Fiction
423,The Life-Changing Magic of Tidying Up: The Jap...,Marie Kondō,4.5,22641,11,2015,Non Fiction
339,The Amateur,Edward Klein,4.6,2580,9,2012,Non Fiction
37,Born to Run,Bruce Springsteen,4.7,3729,18,2016,Non Fiction
295,Secret Garden: An Inky Treasure Hunt and Color...,Johanna Basford,4.7,9366,9,2015,Non Fiction
165,Homebody: A Guide to Creating Spaces You Never...,Joanna Gaines,4.8,3776,22,2018,Non Fiction
197,Killing Kennedy: The End of Camelot,Bill O'Reilly,4.6,8634,25,2012,Non Fiction

In [21]:
def stratified_sampling(df, col, n_samples):
    
    n = min(n_samples, df[col].value_counts().min())
    
    df_groupby = df.groupby(col).apply(lambda x: x.sample(n))
    
    df_groupby.index = df_groupby.index.droplevel(0)
    
    return df_groupby

In [22]:
col = ['Genre']

In [23]:
n_samples = 4

In [24]:
stratified_sample = stratified_sampling(bestsellers_data, col, n_samples)

stratified_sample

,Name,Author,User_Rating,Reviews,Price,Year,Genre
350,The Book with No Pictures,B. J. Novak,4.8,8081,8,2015,Fiction
458,"The Serpent's Shadow (The Kane Chronicles, Boo...",Rick Riordan,4.8,2091,12,2012,Fiction
489,The Wonderful Things You Will Be,Emily Winfield Martin,4.9,8842,10,2019,Fiction
362,The Day the Crayons Quit,Drew Daywalt,4.8,8922,9,2015,Fiction
308,StrengthsFinder 2.0,Gallup,4.0,5069,17,2013,Non Fiction
282,Quiet: The Power of Introverts in a World That...,Susan Cain,4.6,10009,20,2012,Non Fiction
185,Instant Pot Pressure Cooker Cookbook: 500 Ever...,Jennifer Smith,4.4,7396,13,2018,Non Fiction
503,Thug Kitchen: The Official Cookbook: Eat Like ...,Thug Kitchen,4.6,11128,23,2017,Non Fiction

### Cluster Sampling
 - In cluster sampling, the sampling unit is the whole cluster; Instead of sampling individuals from within each group, a researcher will study whole clusters.

In [25]:
bestsellers_data['Year'].unique()

array([2016, 2011, 2018, 2017, 2019, 2014, 2010, 2009, 2015, 2013, 2012])

In [26]:
bestsellers_data['Year'].nunique()

11

In [27]:
bestsellers_data['Year'].value_counts()

2009    50
2010    50
2011    50
2012    50
2013    50
2014    50
2015    50
2016    50
2017    50
2018    50
2019    50
Name: Year, dtype: int64

In [28]:
clusters = np.random.choice(np.arange(2009, 2020), size=4, replace=False)

clusters

array([2015, 2019, 2013, 2017])

In [29]:
cluster_sample = bestsellers_data[bestsellers_data['Year'].isin(clusters)]

In [30]:
cluster_sample.head(10)

,Name,Author,User_Rating,Reviews,Price,Year,Genre
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction
7,A Gentleman in Moscow: A Novel,Amor Towles,4.7,19699,15,2017,Fiction
10,A Man Called Ove: A Novel,Fredrik Backman,4.6,23848,8,2017,Fiction
16,Adult Coloring Book: Stress Relieving Animal D...,Blue Star Coloring,4.6,2925,6,2015,Non Fiction
17,Adult Coloring Book: Stress Relieving Patterns,Blue Star Coloring,4.4,2951,6,2015,Non Fiction
18,Adult Coloring Books: A Coloring Book for Adul...,Coloring Books for Adults,4.5,2426,8,2015,Non Fiction
21,All the Light We Cannot See,Anthony Doerr,4.6,36348,14,2015,Fiction
22,Allegiant,Veronica Roth,3.9,6310,13,2013,Fiction
23,American Sniper: The Autobiography of the Most...,Chris Kyle,4.6,15921,9,2015,Non Fiction

In [31]:
cluster_sample['Year'].value_counts()

2013    50
2015    50
2017    50
2019    50
Name: Year, dtype: int64

### Systematic Sampling
 - Systematic sampling is a probability sampling method where researchers select members of the population at a regular interval

Define total number of covid19_constructed_data:

In [32]:
total = len(bestsellers_data)

total

550

Defining Size of Systematic Sample

In [33]:
samples = 25

Defining Interval(gap) in order to get required data.

In [34]:
interval = (total // samples)

interval

22

Define systematic sampling function

In [35]:
def systematic_sampling(df, start_index, step):
    
    indexes = np.arange(start_index, len(df), step=step)
    
    systematic_sample = df.iloc[indexes]
    
    return systematic_sample

In [36]:
systematic_sample = systematic_sampling(bestsellers_data, 0, interval)

systematic_sample

,Name,Author,User_Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
22,Allegiant,Veronica Roth,3.9,6310,13,2013,Fiction
44,Can't Hurt Me: Master Your Mind and Defy the Odds,David Goggins,4.8,16244,18,2019,Non Fiction
66,Dear Zoo: A Lift-the-Flap Book,Rod Campbell,4.8,10922,5,2018,Fiction
88,Double Down (Diary of a Wimpy Kid #11),Jeff Kinney,4.8,5118,20,2016,Fiction
110,First 100 Words,Roger Priddy,4.7,17323,4,2014,Non Fiction
132,Go Set a Watchman: A Novel,Harper Lee,3.6,14982,19,2015,Fiction
154,"Harry Potter and the Cursed Child, Parts 1 & 2...",J.K. Rowling,4.0,23973,12,2016,Fiction
176,"I Am Confident, Brave & Beautiful: A Coloring ...",Hopscotch Girls,4.8,9737,7,2019,Non Fiction
198,Killing Lincoln: The Shocking Assassination th...,Bill O'Reilly,4.7,9342,10,2011,Non Fiction
220,Little Fires Everywhere,Celeste Ng,4.5,25706,12,2018,Fiction
242,Night (Night),Elie Wiesel,4.7,5178,9,2016,Non Fiction
264,Percy Jackson and the Olympians Paperback Boxe...,Rick Riordan,4.8,548,2,2010,Fiction
286,Ready Player One: A Novel,Ernest Cline,4.6,22536,12,2017,Fiction
308,StrengthsFinder 2.0,Gallup,4.0,5069,17,2013,Non Fiction
330,The 5000 Year Leap,W. Cleon Skousen,4.8,1680,12,2009,Non Fiction
352,The Boys in the Boat: Nine Americans and Their...,Daniel James Brown,4.8,23358,12,2015,Non Fiction
374,The Five Love Languages: How to Express Heartf...,Gary Chapman,4.6,803,9,2009,Non Fiction
396,The Great Gatsby,F. Scott Fitzgerald,4.4,11616,7,2014,Fiction
418,The Last Olympian (Percy Jackson and the Olymp...,Rick Riordan,4.8,4628,7,2009,Fiction
440,The Official SAT Study Guide,The College Board,4.4,1201,40,2011,Non Fiction
462,The Silent Patient,Alex Michaelides,4.5,27536,14,2019,Fiction
484,The Whole30: The 30-Day Guide to Total Health ...,Melissa Hartwig Urban,4.6,7508,16,2016,Non Fiction
506,To Kill a Mockingbird,Harper Lee,4.8,26234,0,2014,Fiction
528,What Pet Should I Get? (Classic Seuss),Dr. Seuss,4.7,1873,14,2015,Fiction

In [37]:
systematic_sample.shape

(25, 7)

In [38]:
def systematic_sampling_random_start(df, num_samples):
    
    start_index = random.randint(0, len(df)-num_samples+1)
    
    step = (len(df)-start_index) // num_samples
    
    print('Generating', num_samples, 
          'samples with a start index of', start_index,
          'and an interval of', step)
    
    indexes = np.arange(start_index, len(df), step=step)
    
    systematic_sample = df.iloc[indexes]
    
    return systematic_sample

Obtain a systematic sample:

In [39]:
systematic_sample = systematic_sampling_random_start(bestsellers_data, 15)

systematic_sample

Generating 15 samples with a start index of 381 and an interval of 11

,Name,Author,User_Rating,Reviews,Price,Year,Genre
381,The Getaway,Jeff Kinney,4.8,5836,0,2017,Fiction
392,The Goldfinch: A Novel (Pulitzer Prize for Fic...,Donna Tartt,3.9,33844,20,2013,Fiction
403,The Help,Kathryn Stockett,4.8,13871,6,2010,Fiction
414,The Immortal Life of Henrietta Lacks,Rebecca Skloot,4.7,9289,9,2012,Non Fiction
425,The Life-Changing Magic of Tidying Up: The Jap...,Marie Kondō,4.5,22641,11,2017,Non Fiction
436,The Mueller Report,The Washington Post,4.6,2744,12,2019,Non Fiction
447,The Pioneer Woman Cooks: Dinnertime - Comfort ...,Ree Drummond,4.8,3428,14,2015,Non Fiction
458,"The Serpent's Shadow (The Kane Chronicles, Boo...",Rick Riordan,4.8,2091,12,2012,Fiction
469,"The Throne of Fire (The Kane Chronicles, Book 2)",Rick Riordan,4.7,1463,10,2011,Fiction
480,The Very Hungry Caterpillar,Eric Carle,4.9,19546,5,2017,Fiction
491,The Wonky Donkey,Craig Smith,4.8,30183,4,2019,Fiction
502,Thug Kitchen: The Official Cookbook: Eat Like ...,Thug Kitchen,4.6,11128,23,2016,Non Fiction
513,"Twilight (The Twilight Saga, Book 1)",Stephenie Meyer,4.7,11676,9,2009,Fiction
524,Watchmen,Alan Moore,4.8,3829,42,2009,Fiction
535,Where the Wild Things Are,Maurice Sendak,4.8,9967,13,2009,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331,8,2016,Non Fiction